# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'connection_type.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_connection_type_window(object):
    def setupUi(self, connection_type_window):
        connection_type_window.setObjectName("connection_type_window")
        connection_type_window.setEnabled(True)
        connection_type_window.resize(339, 302)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(connection_type_window.sizePolicy().hasHeightForWidth())
        connection_type_window.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(connection_type_window)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_frame = QtWidgets.QFrame(connection_type_window)
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.main_frame)
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.selector_frame = QtWidgets.QFrame(self.main_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selector_frame.sizePolicy().hasHeightForWidth())
        self.selector_frame.setSizePolicy(sizePolicy)
        self.selector_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.selector_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.selector_frame.setObjectName("selector_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.selector_frame)
        self.verticalLayout_3.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.connection_type_label = QtWidgets.QLabel(self.selector_frame)
        self.connection_type_label.setObjectName("connection_type_label")
        self.verticalLayout_3.addWidget(self.connection_type_label)
        self.connection_type_list = QtWidgets.QListWidget(self.selector_frame)
        self.connection_type_list.setObjectName("connection_type_list")
        item = QtWidgets.QListWidgetItem()
        self.connection_type_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.connection_type_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.connection_type_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.connection_type_list.addItem(item)
        self.verticalLayout_3.addWidget(self.connection_type_list)
        self.verticalLayout_2.addWidget(self.selector_frame)
        self.button_frame = QtWidgets.QFrame(self.main_frame)
        self.button_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.button_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.button_frame.setObjectName("button_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.button_frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(127, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.next_button = QtWidgets.QPushButton(self.button_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.next_button.sizePolicy().hasHeightForWidth())
        self.next_button.setSizePolicy(sizePolicy)
        self.next_button.setObjectName("next_button")
        self.horizontalLayout.addWidget(self.next_button)
        self.cancel_button = QtWidgets.QPushButton(self.button_frame)
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout.addWidget(self.cancel_button)
        self.verticalLayout_2.addWidget(self.button_frame)
        self.verticalLayout.addWidget(self.main_frame)

        self.retranslateUi(connection_type_window)
        QtCore.QMetaObject.connectSlotsByName(connection_type_window)

    def retranslateUi(self, connection_type_window):
        _translate = QtCore.QCoreApplication.translate
        connection_type_window.setWindowTitle(_translate("connection_type_window", "Connection Type"))
        self.connection_type_label.setText(_translate("connection_type_window", "Select Connection Type:"))
        __sortingEnabled = self.connection_type_list.isSortingEnabled()
        self.connection_type_list.setSortingEnabled(False)
        item = self.connection_type_list.item(0)
        item.setText(_translate("connection_type_window", "ODBC (Using Existing DSN)"))
        item = self.connection_type_list.item(1)
        item.setText(_translate("connection_type_window", "ODBC"))
        item = self.connection_type_list.item(2)
        item.setText(_translate("connection_type_window", "JDBC"))
        item = self.connection_type_list.item(3)
        item.setText(_translate("connection_type_window", "Native Python"))
        self.connection_type_list.setSortingEnabled(__sortingEnabled)
        self.next_button.setText(_translate("connection_type_window", "Next"))
        self.cancel_button.setText(_translate("connection_type_window", "Cancel"))

