# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'create_test_case.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_create_test_case_dialog(object):
    def setupUi(self, create_test_case_dialog):
        create_test_case_dialog.setObjectName("create_test_case_dialog")
        create_test_case_dialog.resize(596, 494)
        self.create_test_case_dialog_layout = QtWidgets.QVBoxLayout(create_test_case_dialog)
        self.create_test_case_dialog_layout.setObjectName("create_test_case_dialog_layout")
        self.main_frame = QtWidgets.QFrame(create_test_case_dialog)
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.main_frame_layout = QtWidgets.QVBoxLayout(self.main_frame)
        self.main_frame_layout.setObjectName("main_frame_layout")
        self.test_case_name_frame = QtWidgets.QFrame(self.main_frame)
        self.test_case_name_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.test_case_name_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.test_case_name_frame.setObjectName("test_case_name_frame")
        self.gridLayout = QtWidgets.QGridLayout(self.test_case_name_frame)
        self.gridLayout.setContentsMargins(0, -1, -1, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.test_case_name_label = QtWidgets.QLabel(self.test_case_name_frame)
        self.test_case_name_label.setObjectName("test_case_name_label")
        self.gridLayout.addWidget(self.test_case_name_label, 0, 0, 1, 1)
        self.test_case_name_line_edit = QtWidgets.QLineEdit(self.test_case_name_frame)
        self.test_case_name_line_edit.setObjectName("test_case_name_line_edit")
        self.gridLayout.addWidget(self.test_case_name_line_edit, 0, 1, 1, 1)
        self.main_frame_layout.addWidget(self.test_case_name_frame)
        self.tabs = QtWidgets.QTabWidget(self.main_frame)
        self.tabs.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabs.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabs.setElideMode(QtCore.Qt.ElideNone)
        self.tabs.setDocumentMode(False)
        self.tabs.setTabBarAutoHide(False)
        self.tabs.setObjectName("tabs")
        self.source_tab = QtWidgets.QWidget()
        self.source_tab.setObjectName("source_tab")
        self.source_tab_layout = QtWidgets.QVBoxLayout(self.source_tab)
        self.source_tab_layout.setObjectName("source_tab_layout")
        self.source_config_frame = QtWidgets.QFrame(self.source_tab)
        self.source_config_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.source_config_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.source_config_frame.setObjectName("source_config_frame")
        self.source_config_frame_layout = QtWidgets.QHBoxLayout(self.source_config_frame)
        self.source_config_frame_layout.setContentsMargins(0, -1, -1, -1)
        self.source_config_frame_layout.setObjectName("source_config_frame_layout")
        self.source_select_connection_label = QtWidgets.QLabel(self.source_config_frame)
        self.source_select_connection_label.setObjectName("source_select_connection_label")
        self.source_config_frame_layout.addWidget(self.source_select_connection_label)
        self.source_connection_combo_box = QtWidgets.QComboBox(self.source_config_frame)
        self.source_connection_combo_box.setObjectName("source_connection_combo_box")
        self.source_config_frame_layout.addWidget(self.source_connection_combo_box)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.source_config_frame_layout.addItem(spacerItem)
        self.source_sort_check_box = QtWidgets.QCheckBox(self.source_config_frame)
        self.source_sort_check_box.setObjectName("source_sort_check_box")
        self.source_config_frame_layout.addWidget(self.source_sort_check_box)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.source_config_frame_layout.addItem(spacerItem1)
        self.source_tab_layout.addWidget(self.source_config_frame)
        self.source_query_label = QtWidgets.QLabel(self.source_tab)
        self.source_query_label.setObjectName("source_query_label")
        self.source_tab_layout.addWidget(self.source_query_label)
        self.source_query_text_edit = QtWidgets.QPlainTextEdit(self.source_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.source_query_text_edit.sizePolicy().hasHeightForWidth())
        self.source_query_text_edit.setSizePolicy(sizePolicy)
        self.source_query_text_edit.setObjectName("source_query_text_edit")
        self.source_tab_layout.addWidget(self.source_query_text_edit)
        self.tabs.addTab(self.source_tab, "")
        self.target_tab = QtWidgets.QWidget()
        self.target_tab.setObjectName("target_tab")
        self.target_tab_layout = QtWidgets.QVBoxLayout(self.target_tab)
        self.target_tab_layout.setObjectName("target_tab_layout")
        self.target_config_frame = QtWidgets.QFrame(self.target_tab)
        self.target_config_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.target_config_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.target_config_frame.setObjectName("target_config_frame")
        self.target_config_frame_layout = QtWidgets.QHBoxLayout(self.target_config_frame)
        self.target_config_frame_layout.setContentsMargins(0, -1, -1, -1)
        self.target_config_frame_layout.setObjectName("target_config_frame_layout")
        self.target_select_connection_label = QtWidgets.QLabel(self.target_config_frame)
        self.target_select_connection_label.setObjectName("target_select_connection_label")
        self.target_config_frame_layout.addWidget(self.target_select_connection_label)
        self.target_connection_combo_box = QtWidgets.QComboBox(self.target_config_frame)
        self.target_connection_combo_box.setObjectName("target_connection_combo_box")
        self.target_config_frame_layout.addWidget(self.target_connection_combo_box)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.target_config_frame_layout.addItem(spacerItem2)
        self.target_sort_check_box = QtWidgets.QCheckBox(self.target_config_frame)
        self.target_sort_check_box.setObjectName("target_sort_check_box")
        self.target_config_frame_layout.addWidget(self.target_sort_check_box)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.target_config_frame_layout.addItem(spacerItem3)
        self.target_tab_layout.addWidget(self.target_config_frame)
        self.target_query_label = QtWidgets.QLabel(self.target_tab)
        self.target_query_label.setObjectName("target_query_label")
        self.target_tab_layout.addWidget(self.target_query_label)
        self.target_query_text_edit = QtWidgets.QPlainTextEdit(self.target_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.target_query_text_edit.sizePolicy().hasHeightForWidth())
        self.target_query_text_edit.setSizePolicy(sizePolicy)
        self.target_query_text_edit.setObjectName("target_query_text_edit")
        self.target_tab_layout.addWidget(self.target_query_text_edit)
        self.tabs.addTab(self.target_tab, "")
        self.main_frame_layout.addWidget(self.tabs)
        self.bottom_frame = QtWidgets.QFrame(self.main_frame)
        self.bottom_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bottom_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottom_frame.setObjectName("bottom_frame")
        self.button_frame_layout = QtWidgets.QHBoxLayout(self.bottom_frame)
        self.button_frame_layout.setObjectName("button_frame_layout")
        self.max_mismatch_size_label = QtWidgets.QLabel(self.bottom_frame)
        self.max_mismatch_size_label.setObjectName("max_mismatch_size_label")
        self.button_frame_layout.addWidget(self.max_mismatch_size_label)
        self.max_mismatch_size_line_edit = QtWidgets.QLineEdit(self.bottom_frame)
        self.max_mismatch_size_line_edit.setObjectName("max_mismatch_size_line_edit")
        self.button_frame_layout.addWidget(self.max_mismatch_size_line_edit)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.button_frame_layout.addItem(spacerItem4)
        self.save_button = QtWidgets.QPushButton(self.bottom_frame)
        self.save_button.setObjectName("save_button")
        self.button_frame_layout.addWidget(self.save_button)
        self.cancel_button = QtWidgets.QPushButton(self.bottom_frame)
        self.cancel_button.setObjectName("cancel_button")
        self.button_frame_layout.addWidget(self.cancel_button)
        self.main_frame_layout.addWidget(self.bottom_frame)
        self.create_test_case_dialog_layout.addWidget(self.main_frame)

        self.retranslateUi(create_test_case_dialog)
        self.tabs.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(create_test_case_dialog)

    def retranslateUi(self, create_test_case_dialog):
        _translate = QtCore.QCoreApplication.translate
        create_test_case_dialog.setWindowTitle(_translate("create_test_case_dialog", "Create New Test Case"))
        self.test_case_name_label.setText(_translate("create_test_case_dialog", "Test Case Name"))
        self.source_select_connection_label.setText(_translate("create_test_case_dialog", "Select Connection:"))
        self.source_sort_check_box.setText(_translate("create_test_case_dialog", "Sort Result"))
        self.source_query_label.setText(_translate("create_test_case_dialog", "Query:"))
        self.tabs.setTabText(self.tabs.indexOf(self.source_tab), _translate("create_test_case_dialog", "Source"))
        self.target_select_connection_label.setText(_translate("create_test_case_dialog", "Select Connection:"))
        self.target_sort_check_box.setText(_translate("create_test_case_dialog", "Sort Result"))
        self.target_query_label.setText(_translate("create_test_case_dialog", "Query:"))
        self.tabs.setTabText(self.tabs.indexOf(self.target_tab), _translate("create_test_case_dialog", "Target"))
        self.max_mismatch_size_label.setText(_translate("create_test_case_dialog", "Max Mismatch Size:"))
        self.save_button.setText(_translate("create_test_case_dialog", "Save"))
        self.cancel_button.setText(_translate("create_test_case_dialog", "Cancel"))

