# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui__self_(object):
    def setupUi(self, _self_):
        _self_.setObjectName("_self_")
        _self_.resize(755, 642)
        self.central_widget = QtWidgets.QWidget(_self_)
        self.central_widget.setObjectName("central_widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.central_widget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.test_project_tree = QtWidgets.QTreeWidget(self.central_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.test_project_tree.sizePolicy().hasHeightForWidth())
        self.test_project_tree.setSizePolicy(sizePolicy)
        self.test_project_tree.setObjectName("test_project_tree")
        self.test_project_tree.headerItem().setText(0, "1")
        self.horizontalLayout_2.addWidget(self.test_project_tree)
        self.frame = QtWidgets.QFrame(self.central_widget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(9, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.test_results_label = QtWidgets.QLabel(self.frame)
        self.test_results_label.setObjectName("test_results_label")
        self.verticalLayout.addWidget(self.test_results_label)
        self.result_table = QtWidgets.QTableWidget(self.frame)
        self.result_table.setAutoFillBackground(False)
        self.result_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.result_table.setDragDropOverwriteMode(False)
        self.result_table.setAlternatingRowColors(True)
        self.result_table.setWordWrap(False)
        self.result_table.setObjectName("result_table")
        self.result_table.setColumnCount(4)
        self.result_table.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.result_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.result_table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.result_table.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.result_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.result_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.result_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.result_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.result_table.setItem(1, 0, item)
        self.result_table.horizontalHeader().setVisible(True)
        self.result_table.horizontalHeader().setCascadingSectionResizes(True)
        self.result_table.horizontalHeader().setHighlightSections(True)
        self.result_table.horizontalHeader().setSortIndicatorShown(False)
        self.result_table.verticalHeader().setVisible(True)
        self.verticalLayout.addWidget(self.result_table)
        self.progress_bar = QtWidgets.QProgressBar(self.frame)
        self.progress_bar.setProperty("value", 24)
        self.progress_bar.setObjectName("progress_bar")
        self.verticalLayout.addWidget(self.progress_bar)
        self.progress_label = QtWidgets.QLabel(self.frame)
        self.progress_label.setObjectName("progress_label")
        self.verticalLayout.addWidget(self.progress_label)
        self.horizontalLayout_2.addWidget(self.frame)
        _self_.setCentralWidget(self.central_widget)
        self.menu_bar = QtWidgets.QMenuBar(_self_)
        self.menu_bar.setGeometry(QtCore.QRect(0, 0, 755, 21))
        self.menu_bar.setObjectName("menu_bar")
        self.file_menu = QtWidgets.QMenu(self.menu_bar)
        self.file_menu.setObjectName("file_menu")
        self.new_menu = QtWidgets.QMenu(self.file_menu)
        self.new_menu.setObjectName("new_menu")
        _self_.setMenuBar(self.menu_bar)
        self.status_bar = QtWidgets.QStatusBar(_self_)
        self.status_bar.setObjectName("status_bar")
        _self_.setStatusBar(self.status_bar)
        self.new_test_case_action = QtWidgets.QAction(_self_)
        self.new_test_case_action.setObjectName("new_test_case_action")
        self.new_connection_action = QtWidgets.QAction(_self_)
        self.new_connection_action.setObjectName("new_connection_action")
        self.new_test_project_action = QtWidgets.QAction(_self_)
        self.new_test_project_action.setObjectName("new_test_project_action")
        self.new_menu.addAction(self.new_test_project_action)
        self.new_menu.addAction(self.new_test_case_action)
        self.new_menu.addAction(self.new_connection_action)
        self.file_menu.addAction(self.new_menu.menuAction())
        self.menu_bar.addAction(self.file_menu.menuAction())

        self.retranslateUi(_self_)
        QtCore.QMetaObject.connectSlotsByName(_self_)

    def retranslateUi(self, _self_):
        _translate = QtCore.QCoreApplication.translate
        _self_.setWindowTitle(_translate("_self_", "MainWindow"))
        self.test_results_label.setText(_translate("_self_", "Test Results"))
        self.result_table.setSortingEnabled(True)
        item = self.result_table.verticalHeaderItem(0)
        item.setText(_translate("_self_", "1"))
        item = self.result_table.verticalHeaderItem(1)
        item.setText(_translate("_self_", "2"))
        item = self.result_table.verticalHeaderItem(2)
        item.setText(_translate("_self_", "3"))
        item = self.result_table.horizontalHeaderItem(0)
        item.setText(_translate("_self_", "ID"))
        item = self.result_table.horizontalHeaderItem(1)
        item.setText(_translate("_self_", "Test Case Name"))
        item = self.result_table.horizontalHeaderItem(2)
        item.setText(_translate("_self_", "Execution Time Stamp"))
        item = self.result_table.horizontalHeaderItem(3)
        item.setText(_translate("_self_", "Status"))
        __sortingEnabled = self.result_table.isSortingEnabled()
        self.result_table.setSortingEnabled(False)
        self.result_table.setSortingEnabled(__sortingEnabled)
        self.progress_label.setText(_translate("_self_", "TextLabel"))
        self.file_menu.setTitle(_translate("_self_", "File"))
        self.new_menu.setTitle(_translate("_self_", "New"))
        self.new_test_case_action.setText(_translate("_self_", "Test Case"))
        self.new_connection_action.setText(_translate("_self_", "Connection"))
        self.new_test_project_action.setText(_translate("_self_", "Test Project"))

