# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(755, 544)
        self.central_widget = QtWidgets.QWidget(main_window)
        self.central_widget.setObjectName("central_widget")
        self.central_widget_layout = QtWidgets.QVBoxLayout(self.central_widget)
        self.central_widget_layout.setObjectName("central_widget_layout")
        self.splitter = QtWidgets.QSplitter(self.central_widget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setOpaqueResize(True)
        self.splitter.setHandleWidth(5)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName("splitter")
        self.test_project_tree_frame = QtWidgets.QFrame(self.splitter)
        self.test_project_tree_frame.setBaseSize(QtCore.QSize(0, 0))
        self.test_project_tree_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.test_project_tree_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.test_project_tree_frame.setObjectName("test_project_tree_frame")
        self.test_project_tree_frame_layout = QtWidgets.QVBoxLayout(self.test_project_tree_frame)
        self.test_project_tree_frame_layout.setObjectName("test_project_tree_frame_layout")
        self.test_project_tree = QtWidgets.QTreeWidget(self.test_project_tree_frame)
        self.test_project_tree.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.test_project_tree.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.test_project_tree.setAnimated(True)
        self.test_project_tree.setObjectName("test_project_tree")
        self.test_project_tree.headerItem().setText(0, "1")
        self.test_project_tree_frame_layout.addWidget(self.test_project_tree)
        self.result_frame = QtWidgets.QFrame(self.splitter)
        self.result_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.result_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.result_frame.setObjectName("result_frame")
        self.result_frame_layout = QtWidgets.QVBoxLayout(self.result_frame)
        self.result_frame_layout.setObjectName("result_frame_layout")
        self.test_results_label = QtWidgets.QLabel(self.result_frame)
        self.test_results_label.setObjectName("test_results_label")
        self.result_frame_layout.addWidget(self.test_results_label)
        self.result_table = QtWidgets.QTableWidget(self.result_frame)
        self.result_table.setAutoFillBackground(False)
        self.result_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.result_table.setDragDropOverwriteMode(False)
        self.result_table.setAlternatingRowColors(True)
        self.result_table.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.result_table.setWordWrap(False)
        self.result_table.setObjectName("result_table")
        self.result_table.setColumnCount(4)
        self.result_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.result_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.result_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.result_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.result_table.setHorizontalHeaderItem(3, item)
        self.result_table.horizontalHeader().setVisible(True)
        self.result_table.horizontalHeader().setHighlightSections(True)
        self.result_table.horizontalHeader().setSortIndicatorShown(False)
        self.result_table.verticalHeader().setVisible(True)
        self.result_frame_layout.addWidget(self.result_table)
        self.progress_bar = QtWidgets.QProgressBar(self.result_frame)
        self.progress_bar.setProperty("value", 24)
        self.progress_bar.setObjectName("progress_bar")
        self.result_frame_layout.addWidget(self.progress_bar)
        self.progress_label = QtWidgets.QLabel(self.result_frame)
        self.progress_label.setObjectName("progress_label")
        self.result_frame_layout.addWidget(self.progress_label)
        self.central_widget_layout.addWidget(self.splitter)
        main_window.setCentralWidget(self.central_widget)
        self.menu_bar = QtWidgets.QMenuBar(main_window)
        self.menu_bar.setGeometry(QtCore.QRect(0, 0, 755, 21))
        self.menu_bar.setObjectName("menu_bar")
        self.file_menu = QtWidgets.QMenu(self.menu_bar)
        self.file_menu.setObjectName("file_menu")
        self.new_menu = QtWidgets.QMenu(self.file_menu)
        self.new_menu.setObjectName("new_menu")
        main_window.setMenuBar(self.menu_bar)
        self.status_bar = QtWidgets.QStatusBar(main_window)
        self.status_bar.setObjectName("status_bar")
        main_window.setStatusBar(self.status_bar)
        self.new_test_project_action = QtWidgets.QAction(main_window)
        self.new_test_project_action.setObjectName("new_test_project_action")
        self.new_test_case_action = QtWidgets.QAction(main_window)
        self.new_test_case_action.setObjectName("new_test_case_action")
        self.new_connection_action = QtWidgets.QAction(main_window)
        self.new_connection_action.setObjectName("new_connection_action")
        self.save_action = QtWidgets.QAction(main_window)
        self.save_action.setObjectName("save_action")
        self.save_as_action = QtWidgets.QAction(main_window)
        self.save_as_action.setObjectName("save_as_action")
        self.exit_action = QtWidgets.QAction(main_window)
        self.exit_action.setObjectName("exit_action")
        self.new_menu.addAction(self.new_test_project_action)
        self.new_menu.addSeparator()
        self.new_menu.addAction(self.new_test_case_action)
        self.new_menu.addAction(self.new_connection_action)
        self.file_menu.addAction(self.new_menu.menuAction())
        self.file_menu.addSeparator()
        self.file_menu.addAction(self.save_action)
        self.file_menu.addAction(self.save_as_action)
        self.file_menu.addSeparator()
        self.file_menu.addAction(self.exit_action)
        self.menu_bar.addAction(self.file_menu.menuAction())

        self.retranslateUi(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "MainWindow"))
        self.test_results_label.setText(_translate("main_window", "Test Results"))
        self.result_table.setSortingEnabled(True)
        item = self.result_table.horizontalHeaderItem(0)
        item.setText(_translate("main_window", "ID"))
        item = self.result_table.horizontalHeaderItem(1)
        item.setText(_translate("main_window", "Test Case Name"))
        item = self.result_table.horizontalHeaderItem(2)
        item.setText(_translate("main_window", "Execution Time Stamp"))
        item = self.result_table.horizontalHeaderItem(3)
        item.setText(_translate("main_window", "Status"))
        self.progress_label.setText(_translate("main_window", "Executing Test Case 2"))
        self.file_menu.setTitle(_translate("main_window", "File"))
        self.new_menu.setTitle(_translate("main_window", "New"))
        self.new_test_project_action.setText(_translate("main_window", "Test Project"))
        self.new_test_project_action.setShortcut(_translate("main_window", "Ctrl+N"))
        self.new_test_case_action.setText(_translate("main_window", "Test Case"))
        self.new_test_case_action.setShortcut(_translate("main_window", "Ctrl+Shift+T"))
        self.new_connection_action.setText(_translate("main_window", "Connection"))
        self.new_connection_action.setShortcut(_translate("main_window", "Ctrl+Shift+C"))
        self.save_action.setText(_translate("main_window", "Save"))
        self.save_action.setShortcut(_translate("main_window", "Ctrl+S"))
        self.save_as_action.setText(_translate("main_window", "Save As.."))
        self.save_as_action.setShortcut(_translate("main_window", "Ctrl+Shift+S"))
        self.exit_action.setText(_translate("main_window", "Exit"))
        self.exit_action.setShortcut(_translate("main_window", "Ctrl+Q"))

