# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'odbcDSN.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_odbc_dsn_dialog(object):
    def setupUi(self, odbc_dsn_dialog):
        odbc_dsn_dialog.setObjectName("odbc_dsn_dialog")
        odbc_dsn_dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        odbc_dsn_dialog.resize(400, 250)
        odbc_dsn_dialog.setMaximumSize(QtCore.QSize(400, 250))
        self.vertical_layout = QtWidgets.QVBoxLayout(odbc_dsn_dialog)
        self.vertical_layout.setObjectName("vertical_layout")
        self.main_frame = QtWidgets.QFrame(odbc_dsn_dialog)
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.main_frame_layout = QtWidgets.QVBoxLayout(self.main_frame)
        self.main_frame_layout.setObjectName("main_frame_layout")
        self.form_frame = QtWidgets.QFrame(self.main_frame)
        self.form_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.form_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.form_frame.setObjectName("form_frame")
        self.formLayout = QtWidgets.QFormLayout(self.form_frame)
        self.formLayout.setObjectName("formLayout")
        self.connection_name_label = QtWidgets.QLabel(self.form_frame)
        self.connection_name_label.setObjectName("connection_name_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.connection_name_label)
        self.connection_name_line_edit = QtWidgets.QLineEdit(self.form_frame)
        self.connection_name_line_edit.setObjectName("connection_name_line_edit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.connection_name_line_edit)
        self.dsn_label = QtWidgets.QLabel(self.form_frame)
        self.dsn_label.setObjectName("dsn_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.dsn_label)
        self.dsn_combo_box = QtWidgets.QComboBox(self.form_frame)
        self.dsn_combo_box.setObjectName("dsn_combo_box")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.dsn_combo_box)
        self.windows_auth_check_box = QtWidgets.QCheckBox(self.form_frame)
        self.windows_auth_check_box.setObjectName("windows_auth_check_box")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.windows_auth_check_box)
        self.user_name_label = QtWidgets.QLabel(self.form_frame)
        self.user_name_label.setObjectName("user_name_label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.user_name_label)
        self.username_line_edit = QtWidgets.QLineEdit(self.form_frame)
        self.username_line_edit.setObjectName("username_line_edit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.username_line_edit)
        self.password_label = QtWidgets.QLabel(self.form_frame)
        self.password_label.setObjectName("password_label")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.password_label)
        self.password_line_edit = QtWidgets.QLineEdit(self.form_frame)
        self.password_line_edit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_line_edit.setObjectName("password_line_edit")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.password_line_edit)
        self.main_frame_layout.addWidget(self.form_frame)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.main_frame_layout.addItem(spacerItem)
        self.button_frame = QtWidgets.QFrame(self.main_frame)
        self.button_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.button_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.button_frame.setObjectName("button_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.button_frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.connect_button = QtWidgets.QPushButton(self.button_frame)
        self.connect_button.setObjectName("connect_button")
        self.horizontalLayout.addWidget(self.connect_button)
        self.save_button = QtWidgets.QPushButton(self.button_frame)
        self.save_button.setEnabled(False)
        self.save_button.setObjectName("save_button")
        self.horizontalLayout.addWidget(self.save_button)
        self.cancel_button = QtWidgets.QPushButton(self.button_frame)
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout.addWidget(self.cancel_button)
        self.main_frame_layout.addWidget(self.button_frame)
        self.vertical_layout.addWidget(self.main_frame)

        self.retranslateUi(odbc_dsn_dialog)
        QtCore.QMetaObject.connectSlotsByName(odbc_dsn_dialog)

    def retranslateUi(self, odbc_dsn_dialog):
        _translate = QtCore.QCoreApplication.translate
        odbc_dsn_dialog.setWindowTitle(_translate("odbc_dsn_dialog", "ODBC DSN Connection"))
        self.connection_name_label.setText(_translate("odbc_dsn_dialog", "Connection Name:"))
        self.dsn_label.setText(_translate("odbc_dsn_dialog", "Data Source Name: "))
        self.windows_auth_check_box.setText(_translate("odbc_dsn_dialog", "Use windows authentication"))
        self.user_name_label.setText(_translate("odbc_dsn_dialog", "Username:"))
        self.password_label.setText(_translate("odbc_dsn_dialog", "Password:"))
        self.connect_button.setText(_translate("odbc_dsn_dialog", "Connect"))
        self.connect_button.setShortcut(_translate("odbc_dsn_dialog", "Return"))
        self.save_button.setText(_translate("odbc_dsn_dialog", "Save"))
        self.save_button.setShortcut(_translate("odbc_dsn_dialog", "Ctrl+S"))
        self.cancel_button.setText(_translate("odbc_dsn_dialog", "Cancel"))
        self.cancel_button.setShortcut(_translate("odbc_dsn_dialog", "Esc"))

