# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'odbc.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_odbc_dialog(object):
    def setupUi(self, odbc_dialog):
        odbc_dialog.setObjectName("odbc_dialog")
        odbc_dialog.resize(420, 329)
        self.odbc_dialog_layout = QtWidgets.QVBoxLayout(odbc_dialog)
        self.odbc_dialog_layout.setObjectName("odbc_dialog_layout")
        self.main_frame = QtWidgets.QFrame(odbc_dialog)
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.main_frame_layout = QtWidgets.QVBoxLayout(self.main_frame)
        self.main_frame_layout.setObjectName("main_frame_layout")
        self.form_frame = QtWidgets.QFrame(self.main_frame)
        self.form_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.form_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.form_frame.setObjectName("form_frame")
        self.form_frame_layout = QtWidgets.QFormLayout(self.form_frame)
        self.form_frame_layout.setObjectName("form_frame_layout")
        self.driver_label = QtWidgets.QLabel(self.form_frame)
        self.driver_label.setObjectName("driver_label")
        self.form_frame_layout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.driver_label)
        self.server_label = QtWidgets.QLabel(self.form_frame)
        self.server_label.setObjectName("server_label")
        self.form_frame_layout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.server_label)
        self.server_line_edit = QtWidgets.QLineEdit(self.form_frame)
        self.server_line_edit.setObjectName("server_line_edit")
        self.form_frame_layout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.server_line_edit)
        self.port_label = QtWidgets.QLabel(self.form_frame)
        self.port_label.setObjectName("port_label")
        self.form_frame_layout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.port_label)
        self.port_line_edit = QtWidgets.QLineEdit(self.form_frame)
        self.port_line_edit.setObjectName("port_line_edit")
        self.form_frame_layout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.port_line_edit)
        self.database_label = QtWidgets.QLabel(self.form_frame)
        self.database_label.setObjectName("database_label")
        self.form_frame_layout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.database_label)
        self.database_line_edit = QtWidgets.QLineEdit(self.form_frame)
        self.database_line_edit.setObjectName("database_line_edit")
        self.form_frame_layout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.database_line_edit)
        self.username_label = QtWidgets.QLabel(self.form_frame)
        self.username_label.setObjectName("username_label")
        self.form_frame_layout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.username_label)
        self.username_line_edit = QtWidgets.QLineEdit(self.form_frame)
        self.username_line_edit.setObjectName("username_line_edit")
        self.form_frame_layout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.username_line_edit)
        self.password_label = QtWidgets.QLabel(self.form_frame)
        self.password_label.setObjectName("password_label")
        self.form_frame_layout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.password_label)
        self.password_line_edit = QtWidgets.QLineEdit(self.form_frame)
        self.password_line_edit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_line_edit.setObjectName("password_line_edit")
        self.form_frame_layout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.password_line_edit)
        self.driver_combo_box = QtWidgets.QComboBox(self.form_frame)
        self.driver_combo_box.setObjectName("driver_combo_box")
        self.form_frame_layout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.driver_combo_box)
        self.connection_name_line_edit = QtWidgets.QLineEdit(self.form_frame)
        self.connection_name_line_edit.setObjectName("connection_name_line_edit")
        self.form_frame_layout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.connection_name_line_edit)
        self.connection_name_label = QtWidgets.QLabel(self.form_frame)
        self.connection_name_label.setObjectName("connection_name_label")
        self.form_frame_layout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.connection_name_label)
        self.windows_auth_check_box = QtWidgets.QCheckBox(self.form_frame)
        self.windows_auth_check_box.setObjectName("windows_auth_check_box")
        self.form_frame_layout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.windows_auth_check_box)
        self.main_frame_layout.addWidget(self.form_frame)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.main_frame_layout.addItem(spacerItem)
        self.button_frame = QtWidgets.QFrame(self.main_frame)
        self.button_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.button_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.button_frame.setObjectName("button_frame")
        self.button_frame_layout = QtWidgets.QHBoxLayout(self.button_frame)
        self.button_frame_layout.setObjectName("button_frame_layout")
        spacerItem1 = QtWidgets.QSpacerItem(116, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.button_frame_layout.addItem(spacerItem1)
        self.connect_button = QtWidgets.QPushButton(self.button_frame)
        self.connect_button.setObjectName("connect_button")
        self.button_frame_layout.addWidget(self.connect_button)
        self.save_button = QtWidgets.QPushButton(self.button_frame)
        self.save_button.setEnabled(False)
        self.save_button.setObjectName("save_button")
        self.button_frame_layout.addWidget(self.save_button)
        self.cancel_button = QtWidgets.QPushButton(self.button_frame)
        self.cancel_button.setObjectName("cancel_button")
        self.button_frame_layout.addWidget(self.cancel_button)
        self.main_frame_layout.addWidget(self.button_frame)
        self.odbc_dialog_layout.addWidget(self.main_frame)

        self.retranslateUi(odbc_dialog)
        QtCore.QMetaObject.connectSlotsByName(odbc_dialog)

    def retranslateUi(self, odbc_dialog):
        _translate = QtCore.QCoreApplication.translate
        odbc_dialog.setWindowTitle(_translate("odbc_dialog", "ODBC Connection"))
        self.driver_label.setText(_translate("odbc_dialog", "Driver:"))
        self.server_label.setText(_translate("odbc_dialog", "Server:"))
        self.port_label.setText(_translate("odbc_dialog", "Port:"))
        self.database_label.setText(_translate("odbc_dialog", "Database:"))
        self.username_label.setText(_translate("odbc_dialog", "Username:"))
        self.password_label.setText(_translate("odbc_dialog", "Password:"))
        self.connection_name_label.setText(_translate("odbc_dialog", "Connection Name:"))
        self.windows_auth_check_box.setText(_translate("odbc_dialog", "Use Windows authentication"))
        self.connect_button.setText(_translate("odbc_dialog", "Connect"))
        self.connect_button.setShortcut(_translate("odbc_dialog", "Return"))
        self.save_button.setText(_translate("odbc_dialog", "Save"))
        self.save_button.setShortcut(_translate("odbc_dialog", "Ctrl+S"))
        self.cancel_button.setText(_translate("odbc_dialog", "Cancel"))
        self.cancel_button.setShortcut(_translate("odbc_dialog", "Esc"))

